# Recommendations

## Formulating Recommendations

Recommendations are formulated using the GRADE approach. 
The categories include strong in favor, conditional in favor, conditional against, and strong against an intervention. 
Strong recommendations reflect the Task Force believing all or almost all clinicians would choose (or not choose) the specific action or approach. 
Conditional recommendations are those where most, but not all, would choose (or not choose) the action or approach.
Recommendations are presented in tabular format accompanied by the strength of recommendation and evidence. 

<!-- SOE supporting the final recommendation is determined by the lowest SOE for any critical outcome. -->
<!-- "It is better to be explicit, and it is logical that the overall confidence in effect estimates cannot be higher than the lowest confidence in effect estimates for any outcome that is critical for a decision. We therefore suggest applying the lowest confidence rating of the critical outcomes as the overall confidence associated with a recommendation."  @Guyatt2013 @oxman2004 -->

<!-- Not a logical approach as outcomes are not weighted equally.  -->


## Best Practice Statements

Although not included in the formal GRADE guidance, its developers recommend guideline panels distinguish good or best practice statements from guideline recommendations.
Best practice statements are those where evidence is inappropriate for a strength of evidence rating.
 


@Brito2013

1. When low quality of evidence suggests benefit in a life-threatening situation. 

2. When low quality of evidence suggests benefit and high quality of evidence suggests harm or with a very high cost. 

3. When low quality of evidence suggests equivalence of 2 alternatives, but high quality evidence of less harm for one of the competing alternatives. 

4. When high quality of evidence suggest equivalence of 2 alternatives and low quality of evidence suggests harm in one alternative. 

5. When low to high quality of evidence suggests benefits in one important outcome (outcome A) and low/very low quality of evidence suggests possibility of harm in critical (outcome B) and the harm regarding outcome B is valued much more highly than any benefit vis-a-vis.

## No Recommendation

@Bretthauer2018

@Neumann2020

## SOE SOR Discordance
