# Preface {.unnumbered}

This manual represents the methods used to develop the American Society of Anesthesiologists (ASA) practice parameters. It describes processes, procedures, and relevant policies overseen by the Committee on Practice Parameters (CPP).

As the methods and approaches evolve, modification are incorporated. Those representing ASA policy or falling under CPP's authority are included only after administrative approval (eg, matters related to conflict of interest or the choice of strength of evidence framework). Other changes, for example evidence synthesis methods, are the purview of methodologists. They are updated as appropriate or when clarifications are necessary. A history of substantive modifications are listed at the end of each chapter (in the online version only).

Comments, suggestions for additions, or corrections can be sent to [Mark Grant](mailto:m.grant@asahq.org).

::: {.content-hidden when-format="pdf"}
::: {.callout-note collapse="true"}
# Modification History

| Date       | Modifications | Version | Note            |
|:-----------|:--------------|:--------|:----------------|
| 2023-07-24 | None          | 0.1     | Initial version |
:::
:::
